### ISSUE TITLE
RxJava 1 bindings for new modules are no longer generated

### ISSUE THREAD

**Issue by InfoSec812** [vert-x3/issues#596] opened 2022-01-30 17:09 UTC
### Version

4.2.3

### Context

When I add the `io.vertx:vertx-rx-java:4.2.3` dependency, I expect that there should be a class something like:

`io.vertx.rxjava.ext.web.openapi.RouterBuilder` which can take `io.vertx.rxjava.core.Vertx` as an argument to it's 'rxCreate` method.

### Do you have a reproducer?

No

### Steps to reproduce

1. Add the `vertx-rx-java` and `vertx-web-openapi` dependencies to a project
2. In a Verticle, attempt to use `RouterBuilder.rxCreate(vertx, "/path/to/openapi.yaml");`

### Extra

* I **DO** see a `io.vertx.reactivex.ext.web.openapi.RouterBuilder` class, but it's `rxCreate` method signatures do not match.

**Comment by tsegismont** [comment] 2022-01-31 09:44
It's seems only the RxJava 2 and 3 bindings are generated: https://github.com/vert-x3/vertx-rx/search?q=vertx-web-openapi

**Comment by tsegismont** [comment] 2022-01-31 09:56
Actually, this is a duplicate of https://github.com/vert-x3/vertx-rx/issues/256

Please upgrade to RxJava 3 (RxJava 1 nor 2 are not supported anymore)

**Comment by InfoSec812** [comment] 2022-01-31 12:32
Ahhhh! Then I highly recommend a big noticeable message on the
documentation pages first them.

Deven

**Comment by tsegismont** [comment] 2022-01-31 13:35
On this one? https://vertx.io/docs/vertx-rx/java/

**Comment by InfoSec812** [comment] 2022-01-31 13:44
I see no notice there... 
![image](https://user-images.githubusercontent.com/99691/151804525-6a3fac50-e03f-46dc-a133-6c47d835b990.png)

**Comment by tsegismont** [comment] 2022-01-31 15:56
I meant: what do you think about adding a notice on vertx-rxjava 1 doc ?

**Comment by InfoSec812** [comment] 2022-01-31 16:06
Yes, I think that makes a great deal of sense if it truly is end-of-life.

**Closed as completed** 2022-03-01 09:56 UTC
Labels: documentation
