### ISSUE TITLE
Chained handlers

### ISSUE THREAD

**Issue by drejc** [vert-x3/issues#254] opened 2017-04-07 06:41 UTC
I have the following routes:

First one work as expected, both handlers are invoked:
```
router.get("/private").handler(new CheckRoleHandler(UserRole.Admin));
router.get("/private").handler(infoHandler); 
```

**I have also tried this:**
```
router.get("/private2").handler(new CheckRoleHandler(UserRole.Admin)).handler(infoHandler);
```

but only the second handler gets invoked and the _CheckRoleHandler_ is skipped.

Don't know if this is by design, but one would expected that all handlers in a given chain are executed ?

**Comment by pmlopes** [comment] 2017-04-07 06:49
You can only add a handler to a route (this is by design but might need to be changed in the future) and there is no proper documentation either. We should for now atleast throw an exception stating that there is already an handler or log a warning at runtime

**Comment by drejc** [comment] 2017-04-07 06:51
Sure ... it took me at least 10min to find the problem ... was going with the second approach.

Would it be this hard to allow chaining? I think it could be useful in some cases ...

**Comment by pmlopes** [comment] 2017-04-07 06:57
For now it will be hard because we need to rework the internals of the route object. The reason is not just to allow multiple handlers but to correctly respond to content negotiation requests https://github.com/vert-x3/vertx-web/issues/456 and also to properly answer to https://github.com/vert-x3/vertx-web/issues/594.

**Comment by pmlopes** [comment] 2017-04-07 06:58
I'll add the exception as proposed above for the next point release and from there we'll start working on the overall issue as described above.

**Comment by pmlopes** [comment] 2017-04-07 07:17
The warning has been already raised to an exception: https://github.com/vert-x3/vertx-web/issues/434

**Comment by pmlopes** [comment] 2017-04-07 07:18
I'll close this since the fix is already on master and the remaining tasks will happen in their own issues.

**Closed as completed by pmlopes** 2017-04-07 07:18 UTC
