### ISSUE TITLE
logback does not work

### ISSUE THREAD

**Issue by roadog** [vert-x3/issues#159] opened 2016-07-23 07:56 UTC
Use the docker image vertx/vertx3:3.3.x.

In Dockerfile use the command 'vertx run $VERTICLE_NAME -cp $VERTICLE_HOME/*' but logback does not work.
# (logback classes in jar)

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by roadog** [comment] 2016-07-23 08:10
Before 3.3.x I solve this problem is to use cmd of ' export CLASSPATH=`find $VERTICLE_HOME -printf '%p:' | sed 's/:$//'`;vertx run $VERTICLE_NAME ....'

I tried 'export CLASSPATH=`find $VERTICLE_HOME -exec printf '{}:' \; | sed 's/:$//'`;vertx run $VERTICLE_NAME...' but failed.

**Comment by alexlehm** [comment] 2016-07-23 10:42
vert.x does not include any slf4j runtime jars, you will have to put your logback runtime JAR into a lib dir 
(or in VERTX_HOME)

**Comment by cescoffier** [comment] 2016-07-24 08:32
As said by @alexlehm, this is the expected behavior. If you want logback, you need to:
- add it to the `lib` directory of the docker container
- put the logback.xml file in the classpath
- if you want Vert.x logs to be written in logback, set the logger delegate to the SLF4J one (http://vertx.io/docs/vertx-core/java/#_logging).

Can you tell me what's failed in the command you try to execute ? Could you print the computed classpath.

**Comment by roadog** [comment] 2016-07-25 09:35
slf4j runtime JAR is already in vertx/vertx v3:3.3.x image, and logback runtime JAR and logback.xml are already in my all-in-one JAR ( created by maven-shade-plugin)

No info for the command failed, the container has exited Immediately(no trace in docker's' logs)

**Comment by cescoffier** [comment] 2016-07-25 11:57
could you share it, or create a reproducer. It's sounds like a bug.

You are creating a all-in-one jar. Is it a fat jar (including vert.x runtime), or just your app and a couple of selected dependencies ?

**Comment by roadog** [comment] 2016-07-26 04:18
Thanks for the reply.

It's not a fat jar, just only my classes and dependencies.
(my Dockerfile CMD is vertx run... not java -jar....)

**Comment by cescoffier** [comment] 2016-07-27 11:14
@roadog can you provide a simple reproducer, so I can have a look and identify the root cause.

**Comment by vietj** [comment] 2017-02-15 23:40
closing since no reproducer was provided.

**Closed as completed by vietj** 2017-02-15 23:40 UTC

**Comment by edewit** [comment] 2019-08-29 08:31
I have this issue as well, I have a strong feeling it's something I'm doing wrong. But I've created this [gist](https://gist.github.com/edewit/e60c0fdf4ba2aeb9bf7699c01adda611) to reproduce the problem

```
$ git clone https://gist.github.com/e60c0fdf4ba2aeb9bf7699c01adda611.git
$ docker build -t vertx-test .
$ docker run -i --rm -p 8080:8080 vertx-test:latest               
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by tsegismont** [comment] 2019-08-29 08:44
@edewit Hi! If your application is fat JAR, don't use the `vert-x3` image. See http://vertx.io/docs/vertx-docker/#_deploying_a_fat_jar

**Comment by edewit** [comment] 2019-08-29 08:51
@tsegismont you are right it's a fat-jar that solves that thanks
