### ISSUE TITLE
Need Option to generate Yaml From the routes

### ISSUE THREAD

**Issue by shailender-arya-del** [vert-x3/issues#245] opened 2017-03-21 08:29 UTC
Hi Would like to have an option in vertx to generate the Swagger documentation from the routes of a running HTTP server. 
It would be great to have this functionality in vertx and improve adaptability and discovery

**Comment by pmlopes** [comment] 2017-03-21 08:43
Duplicate of #137

**Closed as completed by pmlopes** 2017-03-21 08:43 UTC
