### ISSUE TITLE
Vertx.eployVerticle(Verticle verticle, Handler<AsyncResult<String>> completionHandler) creates double the number of verticles

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#360] opened 2018-04-26 18:48 UTC
I am on Vert.x 3.5.0.
I would like to create as many vertcle threads as cores.
So I run this code on startup:
```
 int threads = Runtime.getRuntime().availableProcessors();
 for (int i = 0; i < threads; i++) {
            vertx.deployVerticle(webServerStarter, this::onDeployVerticleHandler);
 }
```

I see threads = 8; And I expect to have 8 verticles in the end of this loop.

when I do not pass any handler like this:
```
vertx.deployVerticle(webServerStarter);
```

The result is as expected.

However when I pass a handler:
```
  vertx.deployVerticle(webServerStarter, this::onDeployVerticleHandler);
```
I end up with 16 verticles.

I debugged it and found that the issue is in
io.vertx.core.impl.DeploymentManager:
```
private <T> void reportResult(Context context, Handler<AsyncResult<T>> completionHandler, AsyncResult<T> result) {
    context.runOnContext(v -> {
      try {
        completionHandler.handle(result);
      } catch (Throwable t) {
        log.error("Failure in calling handler", t);
        throw t;
      }
    });
  }
```

When I get into this method I am not either vert.x-eventloop-thread[0-7]

But when I put a breakpoint on the ```  completionHandler.handle(result); ``` line
I am always on ```vert.x-eventloop-thread[8-15]```
So this call to context.runOnContext actually creates another verticle thread somehow.

**Comment by vietj** [comment] 2018-04-26 19:22
did you count the number of verticle instances created ? (with a println for instance)

**Comment by michaelpog** [comment] 2018-04-26 19:39
I verified with multiple ways.
I put a System.out.println inside onDeployVerticleHandler, and inside a httpServerStarted() from this code :
```
httpServer.requestHandler(router::accept)
                  .exceptionHandler(this::connectionExceptionHandler)
                  .listen(this::httpServerStarted);
```

When I put a breakpoint and System.out in httpServerStarted I am in 0-7 verticles and when I hit a breakpoint in onDeployVerticleHandler it's in 8-15th verticles.
Also if I don't pass the onDeployVerticleHandler I have only 8 verticles
I also see in the IDE very clearly

**Comment by vietj** [comment] 2018-04-26 20:44
can you provide a full reproducer test ?

**Comment by michaelpog** [comment] 2018-04-26 21:08
here https://github.com/michaelpog/vertxdeploybugreproducer :)

**Comment by tsegismont** [comment] 2018-04-27 08:10
This is is not a bug. There is no guarantee that the event loop assigned to your verticle will be used to invoke the `deploy()` callback.

There is, however a big problem in your code: you deploy 8 times the *same* verticle instance. This completely breaks the threading model, which is that a verticle instance should only be executed by a single thread.

If you want to use all cores, provide the number of desired instances in deployment options. See https://vertx.io/docs/vertx-core/java/#_specifying_number_of_verticle_instances

**Comment by vietj** [comment] 2018-04-27 08:29
@tsegismont thomas is right, I was suspecting the same and that's why I asked a reproducer.

if you want to feel safe @michaelpog you can create vertx with less event loops too in VertxOptions

**Comment by michaelpog** [comment] 2018-04-27 16:24
That is very interesting. I've being using Vert.x this way for sometime and it worked out fine. Until I came across this issue.
I'm using Spring so I created that vertical object as a singleton bean and then deployed it many times, and every time I deploy it, I got expected behavior in a sense that for every deployment, a new thread is created and the start method is called.
Is what I'm doing fundamentally incorrect? What other issues can I run into if I deploy the same instance multiple times vs deploying several instances?

Also this https://vertx.io/docs/vertx-core/java/#_specifying_number_of_verticle_instances way just does not work for me.
I need to pass parameters into the Verticle object which are actual objects and not strings
Thank you guys for your help

**Comment by michaelpog** [comment] 2018-04-27 17:04
@vietj  @tsegismont , I changed the reproducer to deploy the verticles according to what you suggested.
And the bug is still there.
I am creating a NEW verticle object for every deploy and the deploy callback is still resulting in creation of more verticles.

So I still think it's a bug.

**Comment by vietj** [comment] 2018-04-27 17:41
if you are calling the method N times and gets N*2 verticle instances then it's a bug and you can give us a reproducer

**Comment by vietj** [comment] 2018-04-27 17:41
I will try the reproducer you provided

**Comment by michaelpog** [comment] 2018-04-27 18:06
@vietj it's the same one (I updated it ) https://github.com/michaelpog/vertxdeploybugreproducer yes I am getting 2*N verticles.

**Comment by vietj** [comment] 2018-04-27 18:58
ok thanks

**Comment by vietj** [comment] 2018-04-27 19:01
the output of your test makes me thing that it creates 8 verticles, since `Current Vertx Thread` is printed by the verticle and I can count only 8 lines

however 16 event loops are used.

**Closed as completed by vietj** 2018-04-27 19:01 UTC

**Comment by michaelpog** [comment] 2018-04-27 19:48
@vietj this is not the behavior I am exhibiting 
![screen shot 2018-04-27 at 12 47 49 pm](https://user-images.githubusercontent.com/7913776/39382088-46d65de2-4a19-11e8-9773-3ccb7ee24321.png)
![screen shot 2018-04-27 at 12 48 06 pm](https://user-images.githubusercontent.com/7913776/39382089-46ee8bec-4a19-11e8-96ab-3ef5f90f3b0f.png)

I clearly see 16 verticles and 16 threads

Unless I misunderstood you. This is not an expected behavior. 
I should see 8 verticles -> 8 eventloops -> 8 threads.

Just the callback is creating more threads, which should not happen.
I'm not sure why this issue is closed. It's a clear bug as I see it

**Comment by vietj** [comment] 2018-04-27 20:32
I think your are misunderstanding two things:

- you create 8 instances of the verticles and there are 8 instances (counting the _Current thread_ lines)
- indeed 16 threads are created because Vert.x creates by default 2 * 8 event loops

the 16 threads are created because you are deploying each verticle separately (instead of using deployment options).

you can restrict the number of event loop threads vertx will create with `Vertx.vertx(new VertxOptions().setEventLoopPoolSize(threads))` instead.

If I do that then I get with your example:

```
Creating 8 threads
Current Vertx Thread vert.x-eventloop-thread-0
Current Vertx Thread vert.x-eventloop-thread-1
Current Vertx Thread vert.x-eventloop-thread-3
Current Vertx Thread vert.x-eventloop-thread-2
Current Vertx Thread vert.x-eventloop-thread-2
Current Vertx Thread vert.x-eventloop-thread-3
Current Vertx Thread vert.x-eventloop-thread-1
Current Vertx Thread vert.x-eventloop-thread-0
Deployed on Vertx Thread vert.x-eventloop-thread-4
Deployed on Vertx Thread vert.x-eventloop-thread-4
Deployed on Vertx Thread vert.x-eventloop-thread-7
Deployed on Vertx Thread vert.x-eventloop-thread-7
Deployed on Vertx Thread vert.x-eventloop-thread-6
Deployed on Vertx Thread vert.x-eventloop-thread-6
Deployed on Vertx Thread vert.x-eventloop-thread-5
Deployed on Vertx Thread vert.x-eventloop-thread-5
```

some verticles are deployed on the same event loop because you create each instance separately and instead you should do :

```
        vertx.deployVerticle(WebServerStarter::new, new DeploymentOptions().setInstances(threads), event -> {
            System.out.println("Deployed on Vertx Thread " + Thread.currentThread().getName());
        });
```

in this case I get:

```
Creating 8 threads
Current Vertx Thread vert.x-eventloop-thread-0
Current Vertx Thread vert.x-eventloop-thread-1
Current Vertx Thread vert.x-eventloop-thread-4
Current Vertx Thread vert.x-eventloop-thread-3
Current Vertx Thread vert.x-eventloop-thread-2
Current Vertx Thread vert.x-eventloop-thread-7
Current Vertx Thread vert.x-eventloop-thread-6
Current Vertx Thread vert.x-eventloop-thread-5
Deployed on Vertx Thread vert.x-eventloop-thread-7
```

you can learn more about context, event loop and threads here https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/output/Demystifying_the_event_loop.adoc

**Comment by michaelpog** [comment] 2018-04-27 20:59
@vietj With what you've suggested I'm getting even stranger behavior
![screen shot 2018-04-27 at 1 57 07 pm](https://user-images.githubusercontent.com/7913776/39384813-e54fb83e-4a22-11e8-92b4-52fd6e543a23.png)

![screen shot 2018-04-27 at 1 57 34 pm](https://user-images.githubusercontent.com/7913776/39384833-f52073ca-4a22-11e8-8428-148c0241a82d.png)
the deploy callback is creating a new thread.

Except because now it's a single call it's creating only one more additional thread.
See the 
```
Deployed on Vertx Thread vert.x-eventloop-thread-8
```
At the end, which is different from what you see

**Comment by michaelpog** [comment] 2018-04-27 21:02
Furthermore, if I remove the callback then I get only 8 threads.
But I get an exception (which I guess should have happened to begin with)
![screen shot 2018-04-27 at 2 00 42 pm](https://user-images.githubusercontent.com/7913776/39384966-63ba2aba-4a23-11e8-83a9-c95fed840a1b.png)

Something is not right here.

In addition, this form ```vertx.deployVerticle(WebServerStarter::new, new DeploymentOptions().setInstances(threads));``` is just not satisfying my needs.
There is not way to pass parameters into the objects constructor or any other way, in fact.
