### ISSUE TITLE
Web connection closed with endless stacktrace

### ISSUE THREAD

**Issue by LarsKrogJensen** [vert-x3/issues#345] opened 2018-03-27 18:22 UTC
Issue created from a discussion in [vertx forum](https://groups.google.com/forum/#!topic/vertx/O4mBjz_B3Bc)

Vertx 3.5.1 and 3.5.0 using netty epoll native driver.

We see a huge, recursive stack trace, when an underlying web connections is closed(?) and the recursive pattern looks like:

```
...
  at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:307)
  at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:166)
...
```

This happens over and over again until a NPE is thrown in HttpServerMettricsImpl.

The issue only happens in production (AWS behind ELB) and only in bursts. Traffic in is fairly constant, but every 5-10 minute a burst of hundreds of these exception is logged. During low traffic hours those bursts happens more rarely.
Have not seen any report that any client is affected, a small gatling script was running for an hour without a single failed request.

I really tried to create a reproducer, but have not succeeded.

```
2018-03-12 14:54:32,057 [ERROR] (p-thread-3) io.vertx.core.impl.ContextImpl    - Unhandled exception
java.lang.NullPointerException: null
        at io.vertx.ext.dropwizard.impl.HttpServerMetricsImpl.responseEnd(HttpServerMetricsImpl.java:55)
        at io.vertx.ext.dropwizard.impl.HttpServerMetricsImpl.responseEnd(HttpServerMetricsImpl.java:34)
        at io.vertx.core.http.impl.Http1xServerConnection.responseComplete(Http1xServerConnection.java:169)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end0(HttpServerResponseImpl.java:416)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:318)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:307)
        at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:166)
        at io.vertx.ext.web.impl.RoutingContextImpl.checkHandleNoMatch(RoutingContextImpl.java:129)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:121)
        at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:452)
        at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:153)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$new$3(BodyHandlerImpl.java:165)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleException(HttpServerRequestImpl.java:425)
        at io.vertx.core.http.impl.Http1xServerConnection.handleException(Http1xServerConnection.java:361)
        at io.vertx.core.net.impl.VertxHandler.lambda$exceptionCaught$0(VertxHandler.java:117)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.VertxHandler.exceptionCaught(VertxHandler.java:110)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1326)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:923)
        at io.netty.channel.VoidChannelPromise.fireException(VoidChannelPromise.java:225)
        at io.netty.channel.VoidChannelPromise.tryFailure(VoidChannelPromise.java:165)
        at io.netty.handler.stream.ChunkedWriteHandler$PendingWrite.fail(ChunkedWriteHandler.java:341)
        at io.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:190)
        at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:198)
        at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:137)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:95)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:105)
        at io.vertx.core.http.impl.Http1xServerConnection.writeToChannel(Http1xServerConnection.java:203)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:122)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end0(HttpServerResponseImpl.java:408)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:318)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:307)
        at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:166)
        at io.vertx.ext.web.impl.RoutingContextImpl.checkHandleNoMatch(RoutingContextImpl.java:129)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:121)
        at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:452)
        at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:153)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$new$3(BodyHandlerImpl.java:165)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleException(HttpServerRequestImpl.java:425)
        at io.vertx.core.http.impl.Http1xServerConnection.handleException(Http1xServerConnection.java:361)
        at io.vertx.core.net.impl.VertxHandler.lambda$exceptionCaught$0(VertxHandler.java:117)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.VertxHandler.exceptionCaught(VertxHandler.java:110)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1326)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:923)
        at io.netty.channel.VoidChannelPromise.fireException(VoidChannelPromise.java:225)
        at io.netty.channel.VoidChannelPromise.tryFailure(VoidChannelPromise.java:165)
        at io.netty.handler.stream.ChunkedWriteHandler$PendingWrite.fail(ChunkedWriteHandler.java:341)
        at io.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:190)
        at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:198)
        at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:137)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
        at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:95)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:105)
        at io.vertx.core.http.impl.Http1xServerConnection.writeToChannel(Http1xServerConnection.java:203)
        at io.vertx.core.net.impl.ConnectionBase.writeToChannel(ConnectionBase.java:122)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end0(HttpServerResponseImpl.java:406)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:318)
        at io.vertx.core.http.impl.HttpServerResponseImpl.end(HttpServerResponseImpl.java:307)
        at io.vertx.ext.web.impl.RoutingContextImplBase.unhandledFailure(RoutingContextImplBase.java:166)
        at io.vertx.ext.web.impl.RoutingContextImpl.checkHandleNoMatch(RoutingContextImpl.java:129)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:121)
        at io.vertx.ext.web.impl.RoutingContextImpl.doFail(RoutingContextImpl.java:452)
        at io.vertx.ext.web.impl.RoutingContextImpl.fail(RoutingContextImpl.java:153)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.lambda$new$3(BodyHandlerImpl.java:165)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handleException(HttpServerRequestImpl.java:425)
        at io.vertx.core.http.impl.Http1xServerConnection.handleClosed(Http1xServerConnection.java:340)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:130)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:143)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
        at io.netty.handler.codec.http.HttpContentEncoder.channelInactive(HttpContentEncoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:917)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by craigbensemann** [comment] 2018-04-08 23:35
This looks like the same problem we are having. We are also unable to reproduce it locally. We upgraded from 3.4.1 to 3.5.1 and started seeing this issue. 

My feeling is that this happens only once another error has occurred so normal requests are unaffected. 

We did notice that io.vertx.core.http.impl.Http1xServerConnection normally checks for a non-null pendingResponse prior to using it but the responseComplete method does not - should it?

Also this method sets the field to be null at the end. We have noticed that the stack trace appears to have looped around through the failureHandler a number of times and the second time this method is called pendingResponse would be null.

**Comment by vietj** [comment] 2018-04-09 06:36
@craigbensemann have you looked at https://github.com/eclipse/vert.x/issues/2365 ?

**Comment by vietj** [comment] 2018-04-09 06:38
I'm going to investigate

**Comment by vietj** [comment] 2018-04-09 06:42
I think that vertx-web is misbehaving but clearly vertx core has a bug.

I believe that currently the request exceptionHandler is called this way:

```
    if (currentRequest != null) {
      currentRequest.handleException(new VertxException("Connection was closed"));
    }
```

and I think it should be executed with a `runOnContext` like it happens for the response in `HttpServerResponseImpl#handleClosed()`

**Comment by vietj** [comment] 2018-04-09 06:54
I am able to reproduce with

```
    Vertx vertx = Vertx.vertx();
    vertx.createHttpServer(new HttpServerOptions().setCompressionSupported(true)).requestHandler(req -> {
      req.exceptionHandler(err -> {
        req.response().end("the-end-message");
      });
    }).listen(8080, ar -> {
      HttpClient client = vertx.createHttpClient();
      HttpClientRequest req = client.put(8080, "localhost", "/somerui", handler -> {

      }).setChunked(true);
      req.sendHead(v -> {
        req.connection().close();
      });
    });
```

**Comment by vietj** [comment] 2018-04-09 07:10
actually it's not exactly the same but I have the loop

**Comment by vietj** [comment] 2018-04-09 08:15
the loop should be fixed by https://github.com/eclipse/vert.x/issues/2373 in vertx core

**Comment by craigbensemann** [comment] 2018-04-11 23:00
Thanks for the quick response. We've deployed a small test and it looks like the problem has gone away. We're deploying a larger number of instances today.

**Closed as completed** 2020-07-30 18:50 UTC
