### ISSUE TITLE
Handling DNS Resolution Errors

### ISSUE THREAD

**Issue by jacekmaza** [vert-x3/issues#349] opened 2018-04-04 09:02 UTC
# Bug Description

There seems to be a bug how the DNS resolution errors are handled.
The error happens only when using the java default/blocking name resolver (`vertx.disableDnsResolver=true`).
After the name is unresolved as many times as the size of the connection pool in the http client, the subsequent calls seem to hang.

This problem is a regression as running it against vertx `3.5.0` works as expected.

# Reproducer

```
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.dns.AddressResolverOptions;
import io.vertx.core.http.HttpClient;
import io.vertx.core.http.HttpClientOptions;
import io.vertx.core.http.HttpClientRequest;
import io.vertx.core.http.HttpServer;

import java.util.concurrent.atomic.AtomicInteger;

public class VertxDnsResolutionBug {
    final static int HTTP_CLIENT_POOL_SIZE = 2;

    public static void main(String[] args) {
        System.setProperty("vertx.disableDnsResolver", "true");

        Vertx vertx = Vertx.vertx(new VertxOptions().setAddressResolverOptions(new AddressResolverOptions().setQueryTimeout(100)));
        HttpClient client = vertx.createHttpClient(new HttpClientOptions().setMaxPoolSize(HTTP_CLIENT_POOL_SIZE));
        HttpServer httpServer = vertx.createHttpServer();

        httpServer.requestHandler(serverRequest -> {
            AtomicInteger counter = new AtomicInteger(0);

            for (int i = 0; i < (HTTP_CLIENT_POOL_SIZE + 1); i++) {
                HttpClientRequest clientRequest = client.getAbs("http://invalid-host-name.foo.bar");
                clientRequest.exceptionHandler(e -> {
                    counter.incrementAndGet();
                    e.printStackTrace();
                });
                clientRequest.handler(response -> {
                    counter.incrementAndGet();
                });
                clientRequest.end();
            }

            vertx.setTimer(5000, id -> {
                serverRequest.response().end("finished calls: " + counter.get());
            });
        });

        httpServer.listen(8080);

    }

}

```

Triggering the code by running 
```
❯ curl http://localhost:8080
finished calls: 2
```
indicates that only 2 of 3 calls finished. The 3rd call seems to hang.
There are also only 2 exceptions in the output:
```
java.net.UnknownHostException: invalid-host-name.foo.bar: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:170)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:49)
	at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:214)
	at io.vertx.core.http.impl.pool.Pool.createConnection(Pool.java:286)
	at io.vertx.core.http.impl.pool.Pool.acquireConnection(Pool.java:185)
	at io.vertx.core.http.impl.pool.Pool.getConnection(Pool.java:144)
	at io.vertx.core.http.impl.ConnectionManager.getConnection(ConnectionManager.java:132)
	at io.vertx.core.http.impl.HttpClientImpl.getConnectionForRequest(HttpClientImpl.java:967)
	at io.vertx.core.http.impl.HttpClientRequestImpl.connect(HttpClientRequestImpl.java:638)
	at io.vertx.core.http.impl.HttpClientRequestImpl._write(HttpClientRequestImpl.java:818)
	at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:771)
	at io.vertx.core.http.impl.HttpClientRequestImpl.end(HttpClientRequestImpl.java:746)
	at VertxDnsResolutionBug.lambda$main$3(VertxDnsResolutionBug.java:33)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:433)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:141)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:683)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:636)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:952)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:60)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
java.net.UnknownHostException: invalid-host-name.foo.bar
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:146)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:143)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:143)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:43)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:170)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:49)
	at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:214)
	at io.vertx.core.http.impl.pool.Pool.createConnection(Pool.java:286)
	at io.vertx.core.http.impl.pool.Pool.acquireConnection(Pool.java:185)
	at io.vertx.core.http.impl.pool.Pool.getConnection(Pool.java:144)
	at io.vertx.core.http.impl.ConnectionManager.getConnection(ConnectionManager.java:132)
	at io.vertx.core.http.impl.HttpClientImpl.getConnectionForRequest(HttpClientImpl.java:967)
	at io.vertx.core.http.impl.HttpClientRequestImpl.connect(HttpClientRequestImpl.java:638)
	at io.vertx.core.http.impl.HttpClientRequestImpl._write(HttpClientRequestImpl.java:818)
	at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:771)
	at io.vertx.core.http.impl.HttpClientRequestImpl.end(HttpClientRequestImpl.java:746)
	at VertxDnsResolutionBug.lambda$main$3(VertxDnsResolutionBug.java:33)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:433)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:141)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:683)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:636)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:952)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:60)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Triggering it again
```
❯ curl http://localhost:8080
finished calls: 0
```
results in 0 completed calls.

**Comment by tsegismont** [comment] 2018-04-05 11:48
Can you clarify what your expectation is? Also, the code works as you expect when you run with `3.5.0` but doesn't with `3.5.1`, correct?

**Comment by jacekmaza** [comment] 2018-04-05 12:56
Yes, it used to work fine with `3.5.0`.

In general the expectation is that the application is able to recover from temporary DNS errors. 

When the name resolution fails, our application flow crashes with the `500` which is fine.  With the `3.5.1` however, the `clientRequest.exceptionHandler` is called only for the first few DNS failures (the number seems to be correlated to the connection pool size). The subsequent calls hang - neither `clientRequest.handler` nor `clientRequest.exceptionHandler` is called, so it's not possible to send feedback to the user. Also when the DNS problem recovers the application stays in this broken state.

**Comment by tsegismont** [comment] 2018-04-06 13:50
@jacekmaza thank you. I could reproduce. @vietj will take care of it

**Comment by vietj** [comment] 2018-04-06 14:16
I will open an issue on the vertx repository and link to this one. thanks for reporting.

**Comment by vietj** [comment] 2018-04-06 14:22
it seems to be related indeed to the blocking and synchronous resolver only

**Comment by vietj** [comment] 2018-04-07 08:42
fixed by https://github.com/eclipse/vert.x/issues/2370 - thanks for the reproducer

**Closed as completed by vietj** 2018-04-07 08:42 UTC
Labels: bug

**Comment by jacekmaza** [comment] 2018-04-10 08:13
@vietj, thanks for taking care of it. 

Is there any workaround to get it working with the `3.5.1` or the only option is to wait for `3.6.0` release? By a workaround I mean for example registering an additional exception handler that would make sure the connection is not blocked in case of this particular error case.

**Comment by vietj** [comment] 2018-04-10 08:27
we are thinking doing a 3.5.2 with these bug fixes

**Comment by vietj** [comment] 2018-04-10 08:27
@jacekmaza you could try set a timeout on the `HttpClientRequest`

**Comment by jacekmaza** [comment] 2018-04-10 08:41
The timeout `HttpClientRequest` indeed triggers the error handler. I'll give it a try and see if we can use it for our use case before the bug fix is released.
