### ISSUE TITLE
Converting object containing value of java.time.LocalDateTime Datatype to io.vertx.core.json.JsonObject gives complex Date/Time fields & values

### ISSUE THREAD

**Issue by rpgayatri** [vert-x3/issues#317] opened 2018-01-05 04:13 UTC
I created a map having one of the values of type java.time.LocalDateTime and converted it to Vertx JsonObject. The code is as below :

```
@Test
	public void localDateTimeTest() {
		
		LocalDateTime time = LocalDateTime.now();
		
		Map<Object, Object> newmap = new HashMap<>();
		newmap.put("time", time);
		newmap.put("name", "test");
		
		JsonObject answerObj = JsonObject.mapFrom(newmap);
		
		System.out.println("json::"+answerObj);
	}
```

I get the following output : 
`json::{"name":"test","time":{"year":2018,"monthValue":1,"month":"JANUARY","dayOfMonth":5,"dayOfYear":5,"dayOfWeek":"FRIDAY","hour":15,"minute":6,"second":45,"nano":53000000,"chronology":{"id":"ISO","calendarType":"iso8601"}}}
`

I am getting the date value in complex year/monthValue/month/dayOfMonth format instead of getting just "2018-01-05T04:06:45.555".

I am using the latest vertx version. Kindly help me fix this issue.

**Comment by tsegismont** [comment] 2018-01-05 10:38
@rpgayatri the only temporal type allowed in `JsonObject`/`JsonArray` is Java 8's `Instant` which is encoded to a ISODate String as per the JSON spec extension.

In your example you could simply convert the `time` object to an Instant.

Otherwise, if you map from custom classes (not just a map), you could use a custom serializer.

**Comment by tsegismont** [comment] 2018-01-05 10:39
Marking as invalid since this is a question, not a bug. Please use the user group for further questions (see http://vertx.io/community)

**Closed as completed by tsegismont** 2018-01-05 10:39 UTC
