### ISSUE TITLE
Don't capture stack trace for exception for connection close events

### ISSUE THREAD

**Issue by michaelpog** [vert-x3/issues#358] opened 2018-04-24 18:47 UTC
When I upgraded my application from Vert.x 3.5.0 to 3.5.1. I have noticed a significant performance degradation. (It's na HTTP server and HTTP client application).

I've been investigating the root cause of the degradation  (much higher CPU usage) for a few days now, and I still can't find the definite root cause.

However when comparing Java Flight Recordings I noticed that in Vertx 3.5.1 there is a very very large number of ``` io.vert.xcore.VertxException ```

The stack trace shows this:
```
Stack Trace	Count
java.lang.Throwable.<init>(String)	15,838
   java.lang.Exception.<init>(String)	15,838
      java.lang.RuntimeException.<init>(String)	15,838
         io.vertx.core.VertxException.<init>(String)	15,838
            io.vertx.core.http.impl.Http1xClientConnection.handleClosed()	15,838
               io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(boolean, PoolMetrics, Object, ContextTask, Handler)	15,838
                  io.vertx.core.impl.ContextImpl.executeFromIO(ContextTask)	15,838
                     io.vertx.core.net.impl.VertxHandler.channelInactive(ChannelHandlerContext)	15,838
                        io.vertx.core.http.impl.Http1xClientHandler.channelInactive(ChannelHandlerContext)	15,838
                           io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	15,838
                              io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	15,838
                                 io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	15,838
                                    io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	15,838
                                       io.netty.handler.timeout.IdleStateHandler.channelInactive(ChannelHandlerContext)	15,838
                                          io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	15,838
                                             io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	15,838
                                                io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	15,838
                                                   io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext)	15,838
                                                      io.netty.handler.codec.http.HttpContentDecoder.channelInactive(ChannelHandlerContext)	15,838
                                                         io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	15,838
                                                            io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	15,838
                                                               io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	15,838
                                                                  io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive()	15,838
                                                                     io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ChannelHandlerContext, boolean)	15,838
                                                                        io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ChannelHandlerContext)	15,838
                                                                           io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(ChannelHandlerContext)	15,838
                                                                              io.netty.channel.CombinedChannelDuplexHandler.channelInactive(ChannelHandlerContext)	15,838
                                                                                 io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	15,838
                                                                                    io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	15,838
                                                                                       io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive()	15,838
                                                                                          io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(ChannelHandlerContext)	15,838
                                                                                             io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive()	15,838
                                                                                                io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext)	15,838
                                                                                                   io.netty.channel.DefaultChannelPipeline.fireChannelInactive()	15,838
                                                                                                      io.netty.channel.AbstractChannel$AbstractUnsafe$8.run()	15,838
                                                                                                         io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Runnable)	15,838
                                                                                                            io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(long)	15,838
                                                                                                               io.netty.channel.nio.NioEventLoop.run()	15,838
                                                                                                                  io.netty.util.concurrent.SingleThreadEventExecutor$5.run()	15,838
                                                                                                                     io.netty.util.concurrent.FastThreadLocalRunnable.run()	15,838
                                                                                                                        java.lang.Thread.run()	15,838
```

And in the Events log I see
```
Name	Value	Identifier	Content Type	Relational Key
Class	io.vertx.core.VertxException	thrownClass	class	
Message	Connection was closed	message	text	
Event Thread	vert.x-eventloop-thread-0	(thread)	thread	
   	Throwable.<init>(String) line: 267			
   	Exception.<init>(String) line: 66			
   	RuntimeException.<init>(String) line: 62			
   	VertxException.<init>(String) line: 31			
   	Http1xClientConnection.handleClosed() line: 660			
   	ContextImpl.lambda$wrapTask$2(boolean, PoolMetrics, Object, ContextTask, Handler) line: 337			
   	ContextImpl.executeFromIO(ContextTask) line: 195			
   	VertxHandler.channelInactive(ChannelHandlerContext) line: 130			
   	Http1xClientHandler.channelInactive(ChannelHandlerContext) line: 88			
   	AbstractChannelHandlerContext.invokeChannelInactive() line: 245			
   	AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext) line: 231			
   	AbstractChannelHandlerContext.fireChannelInactive() line: 224			
   	ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext) line: 75			
   	IdleStateHandler.channelInactive(ChannelHandlerContext) line: 277			
   	AbstractChannelHandlerContext.invokeChannelInactive() line: 245			
   	AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext) line: 231			
   	AbstractChannelHandlerContext.fireChannelInactive() line: 224			
   	ChannelInboundHandlerAdapter.channelInactive(ChannelHandlerContext) line: 75			
   	HttpContentDecoder.channelInactive(ChannelHandlerContext) line: 205			
   	AbstractChannelHandlerContext.invokeChannelInactive() line: 245			
   	AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext) line: 231			
   	AbstractChannelHandlerContext.fireChannelInactive() line: 224			
   	CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive() line: 420			
   	ByteToMessageDecoder.channelInputClosed(ChannelHandlerContext, boolean) line: 377			
   	ByteToMessageDecoder.channelInactive(ChannelHandlerContext) line: 342			
   	HttpClientCodec$Decoder.channelInactive(ChannelHandlerContext) line: 282			
   	CombinedChannelDuplexHandler.channelInactive(ChannelHandlerContext) line: 223			
   	AbstractChannelHandlerContext.invokeChannelInactive() line: 245			
   	AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext) line: 231			
   	AbstractChannelHandlerContext.fireChannelInactive() line: 224			
   	DefaultChannelPipeline$HeadContext.channelInactive(ChannelHandlerContext) line: 1354			
   	AbstractChannelHandlerContext.invokeChannelInactive() line: 245			
   	AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext) line: 231			
   	DefaultChannelPipeline.fireChannelInactive() line: 917			
   	AbstractChannel$AbstractUnsafe$8.run() line: 822			
   	AbstractEventExecutor.safeExecute(Runnable) line: 163			
   	SingleThreadEventExecutor.runAllTasks(long) line: 404			
   	NioEventLoop.run() line: 463			
   	SingleThreadEventExecutor$5.run() line: 886			
   	FastThreadLocalRunnable.run() line: 30			
   	Thread.run() line: 745			
```

I still cannot say that this is the reason for the performance degradation, but just looking at this code
in Http1xClientConnection
```
protected synchronized void handleClosed() {
    super.handleClosed();
    if (ws != null) {
      ws.handleClosed();
    }
    retryPending();

    Exception e = new VertxException("Connection was closed");

    // Signal requests failed
    if (metrics != null) {
      for (StreamImpl req: inflight) {
        metrics.requestReset(req.request.metric());
      }
      if (currentResponse != null) {
        metrics.requestReset(currentResponse.request.metric());
      }
    }

    // Connection was closed - call exception handlers for any requests in the pipeline or one being currently written
    for (StreamImpl req: inflight) {
      if (req != currentRequest) {
        req.request.handleException(e);
      }
    }
    if (currentRequest != null) {
      currentRequest.request.handleException(e);
    } else if (currentResponse != null && currentResponse.response != null) {
      currentResponse.response.handleException(e);
    }
  }
```
I attached a debugger, and I see that this VertxException is created, which gets the stack trace (a pretty expensive operation as far as I know)
but in mu case, 
```
metrics == null
currentResponse == null
inflight is empty
```
So this exception object is created and not used anywhere.
 
I think it would make sense to do this:
```
 protected synchronized void handleClosed() {
    super.handleClosed();
    if (ws != null) {
      ws.handleClosed();
    }
    retryPending();

    // Signal requests failed
    if (metrics != null) {
      for (StreamImpl req: inflight) {
        metrics.requestReset(req.request.metric());
      }
      if (currentResponse != null) {
        metrics.requestReset(currentResponse.request.metric());
      }
    }

    // Connection was closed - call exception handlers for any requests in the pipeline or one being currently written
    for (StreamImpl req: inflight) {
      if (req != currentRequest) {
        req.request.handleException(new VertxException("Connection was closed"););
      }
    }
    if (currentRequest != null) {
      currentRequest.request.handleException(e);
    } else if (currentResponse != null && currentResponse.response != null) {
      currentResponse.response.handleException(new VertxException("Connection was closed"););
    }
  }
```
or initialize a supplier once, and call that supplier method where necessary.

Looking at current master
https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/http/impl/Http1xClientConnection.java#L728

Looks like the same problem may be there as well.
Why do we even need this exception there?

**Comment by vietj** [comment] 2018-04-24 19:46
I think we could create a NoStackTraceException which is cheaper to create in most place we need that

**Comment by michaelpog** [comment] 2018-04-24 19:53
Either way is fine, I'm just not sure why this exception is created there, in a high QPS it just adds an unnecessary garbage and overhead.
Thanks @vietj

**Comment by vietj** [comment] 2018-04-24 20:02
I think that wasn't an issue before 3.5.1 that close the connection when they are put back in the pool, I'll do a fix that will be in 3.5.2

**Comment by michaelpog** [comment] 2018-04-24 20:02
On a separate note, @vietj are there any known issues with 3.5.1 that may cause a performance degradation? Any large allocations that may have been introduced? Any issues with the connection pools? I get a very large number of timeouts in HTTP client. The CPU usage is very high. G1GC pause times have increased.
I'm going to test 3.6.0-SNAPSHOT..

**Comment by manish-panwar** [comment] 2018-04-24 20:05
We had to rollback our Prod from 3.5.1 to 3.5.0 within a day due to CPU spike. We were never able to reproduce CPU spike in our load test environment even though we simulated connection errors etc. Definitely something is wrong with 3.5.1, but we couldn't figure it out. See https://groups.google.com/forum/#!searchin/vertx/CPU%7Csort:date/vertx/FOFCDs4EZDc/NqkAGB6KBwAJ (in the post it's mentioned that issue happened in Load Test env, but actually it happened in Prod).

Also see https://groups.google.com/forum/#!topic/vertx/v4D1I8yKy0M

**Comment by vietj** [comment] 2018-04-24 20:09
@michaelpog there is also now 3.5.2-SNAPSHOT

@manish-panwar @michaelpog if you can use java flight recorder to provide a recording it would be great (that you can send me privately)

**Comment by michaelpog** [comment] 2018-04-24 20:25
@manish-panwar thanks for sharing. @vietj I will try to provide you JFR (I'll send it to your email). However I've been staring at those Java Flight Recordings for a few days already and I don't see the root cause.
In fact in many cases I can't even get the recording file because it's too big and JMC cannot open it.

**Comment by manish-panwar** [comment] 2018-04-24 20:30
@michaelpog - You can try recording just for 5-10 minutes. It's difficult for me to provide because issue only happens in Prod box and I will have to go through legal department.

**Comment by vietj** [comment] 2018-04-24 20:32
yes, only for a short period of time is enough

**Comment by michaelpog** [comment] 2018-04-24 20:33
@manish-panwar for some reason even 2 minutes becomes too much. Whenever I put my application on Vert.x 3.5.1 I just hardly get anything from Mission Control. I see very high CPU usage and the file I get is either broken, or JMC tells me it's too big and it was compressed, it tries to decompress and then it tells me it's still too big.So I always see a portion.
I'll try to provide something

**Comment by vietj** [comment] 2018-04-24 20:35
in what kind of workload and application do you observe that ?

**Closed as completed** 2018-04-24 20:38 UTC

**Comment by vietj** [comment] 2018-04-24 20:52
this issue has been fixed in vertx-core master and 3.5 branches

**Comment by manish-panwar** [comment] 2018-04-24 21:06
@michaelpog - In that case could you please try 3.5.2-SNAPSHOT if issue goes away? Since @vietj has marked it closed for 3.5.2, we want to make sure that it's indeed fixed. I can also try but issue only happens in Prod for us (I mean, only in customer's environment), so it's difficult for me to test the SNAPSHOT in prod. Thanks a lot for your help!!!

**Comment by michaelpog** [comment] 2018-04-24 21:11
I'll do my best @vietj @manish-panwar

**Comment by vietj** [comment] 2018-04-24 21:19
@michaelpog if you can describe your application and the workload I can try reproduce something in our performance lab as well

**Comment by michaelpog** [comment] 2018-04-24 21:20
It's a multiplexing HTTP proxy. It takes an HTTP request and transforms into 40 outbound requests downstream.
Some of them are going to timeout which is part of the stress test.
After ~200ms the application aggregates whatever response it got and sends back upstream

**Comment by vietj** [comment] 2018-04-24 21:22
what is the actual workload on the app ? perhaps you can share it for testing along with the client  (wrk ?)

**Comment by michaelpog** [comment] 2018-04-24 21:37
I'm sending 300 QPS inbound. the workload may contain sensitive information I cannot share, unfortunately but it's a json post request. (and the outbound requests are also post json requests and json responses)

**Comment by vietj** [comment] 2018-04-24 21:45
can you describe the inbound (server) and outbound (client) capacity ? i.e the number of connections / hosts

**Comment by michaelpog** [comment] 2018-04-24 21:58
Inbound, one server. outbound (I'm also using one server, but each request goes to a different port)
My connection pool is 60000, 8 vert.x threads. each one is an HTTP server and client.

**Comment by michaelpog** [comment] 2018-04-24 22:04
I'm having issues with my environment right now. So I'll continue updating once it's fixed.

**Comment by vietj** [comment] 2018-04-25 07:57
so 60,000 * 8 possible outbound connections ?

**Comment by michaelpog** [comment] 2018-04-25 14:32
Yes, that's just a lab setting, for the stress test environment.

**Comment by michaelpog** [comment] 2018-04-25 17:36
I'm testing 3.5.2-SNAPSHOT, so far it looks good actually, let me do more testing

**Comment by michaelpog** [comment] 2018-04-25 19:03
@vietj @manish-panwar I have tested 3.5.2-SNAPSHOT, looks like everything is good there. Looks pretty stable, and the performance is as good as 3.5.0. I've shared JFRs with @vietj, I am still clueless why 3.5.1's performance is worse.

**Comment by vietj** [comment] 2018-04-25 22:09
thanks, looking forward to hear from your feedback

**Comment by michaelpog** [comment] 2018-04-25 22:37
@manish-panwar. If it helps, I tested my application with a high  and increasing load, which takes a lot of HTTP requests and sends out a lot of HTTP request outbound.
At the peak it actually performed a bit better with 3.5.2-SNAPSHOT than 3.5.0.  
All our metrics looked the same more or less when comparing 3.5.0 and 3.5.2-SNAPSHOT.
So I'm waiting for 3.5.2 to come out. Unfortunately I still have no idea what was the issue with 3.5.1 but I don't see it with 3.5.2.

**Comment by vietj** [comment] 2018-04-26 09:01
I think the issue with 3.5.1 was the removal of keep-alive support.

Good news for the perf improvements you saw!

3.6.0 should even be better since it has other perf improvements.

**Comment by michaelpog** [comment] 2018-04-26 17:08
3.5.1 removed keep-alive? I am so curious to know why would that be removed? It's such an important feature. I have never worked with keep-alive turned off, and it's so counter intuitive as the property was still there in the HttpClientOptions and it was set to true.

**Comment by vietj** [comment] 2018-04-26 18:11
ah no, actually, with 3.5.1 connection keep alive was used but when a connection was put back in the pool with no outstanding requests, it was closed.

**Comment by manish-panwar** [comment] 2018-04-26 18:34
@michaelpog - Change was done part of this https://github.com/eclipse/vert.x/issues/2208, and when we reported this https://groups.google.com/forum/#!topic/vertx/edVHHS5J7wU then @vietj implemented a timeout for connection to remain in the pool.

Although if you do JFR, you won't know why CPU is high, but I assume "closing connection while putting back in pool" was causing the CPU spike.

**Comment by vietj** [comment] 2018-04-26 19:19
I think the exception creation on close was the main culprit.

**Comment by michaelpog** [comment] 2018-04-26 21:38
Oh interesting, so the one I reported in this issue?

**Comment by vietj** [comment] 2018-04-26 21:54
both and more

**Comment by michaelpog** [comment] 2018-04-26 21:57
Well, I'm glad it's all fixed. Thank you!
