### ISSUE TITLE
error on vertx sendMail, io.vertx.core.impl.ContextImpl - Unhandled exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by vincensiusadi** [vert-x3/issues#395] opened 2018-08-03 07:42 UTC
hello i cannot catch null error on sending email
my code is like this :
```
fun sendMessage(data: JsonObject) : Observable<MailResult> {
         return observable<MailResult> {
            val message = MailMessage(data)
            mailClient.sendMail(message, it)
         }.doOnError {
             log.error("error on mailClient, move to resend"+it.message + " "+ it.getStackTraceAsString())
         }.onErrorReturn {
             null
         }.map {
             it
         }
    }
```
log error : 

```
io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:171)
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:167)
    at io.vertx.ext.mail.impl.SMTPConnection.lambda$null$2(SMTPConnection.java:203)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```
vertx version : 3.5.3
i cannot found what error is this, i cannot catch the error on "doOnError" please help.
Thanks

**Comment by tsegismont** [comment] 2018-08-03 10:28
You can set your own exception handler on the verticle context: https://vertx.io/docs/apidocs/io/vertx/core/Context.html#exceptionHandler-io.vertx.core.Handler-

But it seems the root cause is suppressed here. Can you debug to find what is the null object?

**Comment by vincensiusadi** [comment] 2018-08-03 11:51
i just try this, but still cannot catch the error
```
mailClient.sendMail(message) {
             if (it.succeeded()) {} 
             else {
                  log.error("error on mailClient "+it.cause().printStackTrace())
             }
}
```

**Comment by tsegismont** [comment] 2018-08-03 13:36
Right, if the cause was present I believe it would have printed by the default exception handler. Any progress with debugging?

**Comment by vincensiusadi** [comment] 2018-08-04 02:02
can you give an example code how to debug with default exception handler ? i confused how code it in my code

**Comment by tsegismont** [comment] 2018-08-06 10:04
I meant using a debugger (with a NullPointerException break point for
example)

**Comment by vincensiusadi** [comment] 2018-08-08 15:25
hi,  i catch the error, but different : 

```
null java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
java.util.HashMap$KeyIterator.next(HashMap.java:1461)
io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection0(SMTPConnectionPool.java:133)
io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection(SMTPConnectionPool.java:77)
io.vertx.ext.mail.impl.MailClientImpl.getConnection(MailClientImpl.java:101)
io.vertx.ext.mail.impl.MailClientImpl.sendMail(MailClientImpl.java:91)
```
this is random error when i send milion emails,
what error is this?

**Comment by tsegismont** [comment] 2018-08-09 14:03
Closing, now tracked in https://github.com/vert-x3/vertx-mail-client/issues/95

**Closed as completed by tsegismont** 2018-08-09 14:03 UTC
Labels: duplicate
