### ISSUE TITLE
Is there a vertx-rx-java2 module? vertx-rx-java still using RxJava 1.2.7

### ISSUE THREAD

**Issue by junglie85** [vert-x3/issues#273] opened 2017-06-21 17:54 UTC
Is there a vertx-rx-java2 module? I see a RxJava2 branch in the GitHub repo, but I can;t find anything on jcenter or mavenCentral. I see it's been asked about a few times previously but there doesn't seem to be any update on the status of this project since before Feb. Is it going to be available any time soon? Thanks.

**Comment by vietj** [comment] 2017-06-21 21:34
@AshleyByeUK RxJava 2 support is expected for Vert.x 3.5.0, there is an rxjava2 branch in the vert-x3/rx-java project you can try

**Comment by junglie85** [comment] 2017-06-22 06:21
That's great, thanks. Yes, I'd seen the branch in vert-x3/rx-java and wondered when it was going to hit the main release. Is 3.5.0 due any time soon? I see from the commit comments that a 3.5.0-SNAPSHOT was taken 6 days ago - looking forward to this being generally available.

**Comment by vietj** [comment] 2017-06-22 06:46
we aim to have GA by fall, but publish a beta or milestone over the summer. in the meantime you can subscribe to the vertx-dev list, where we'll share progress on this effort

**Comment by junglie85** [comment] 2017-06-23 12:44
Okay, thanks. I'll keep an eye out for it. Found the [roadmap](https://github.com/vert-x3/wiki/wiki/Vert.x-Roadmap) the other day, which will have answered most of my questions!

**Comment by vietj** [comment] 2017-06-23 13:31
@AshleyByeUK the rxjava2 branch has been just refreshed with a first push and you can try to give feedback

**Comment by junglie85** [comment] 2017-06-23 19:14
Will do, many thanks.

**Comment by junglie85** [comment] 2017-06-23 20:29
Fails `mvn clean install` with:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/ash/IdeaProjects/vertx/vertx-rx/rxjava2/src/test/java/io/vertx/reactivex/test/ApiTest.java:[63,82] incompatible types: io.reactivex.Single<java.lang.String> cannot be converted to io.reactivex.Maybe<java.lang.String>
[ERROR] /Users/ash/IdeaProjects/vertx/vertx-rx/rxjava2/src/test/java/io/vertx/reactivex/test/ApiTest.java:[69,68] incompatible types: io.reactivex.Single<java.lang.String> cannot be converted to io.reactivex.Maybe<java.lang.String>
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Vert.x Reactive Extensions ......................... SUCCESS [  1.301 s]
[INFO] Vert.x RxJava API .................................. SUCCESS [ 50.591 s]
[INFO] Vert.x RxJava2 API ................................. FAILURE [ 15.718 s]
[INFO] Vert.x RxGroovy API ................................ SKIPPED
[INFO] Vert.x RxJs API .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:07 min
[INFO] Finished at: 2017-06-23T20:23:38+01:00
[INFO] Final Memory: 74M/991M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project vertx-rxjava2: Compilation failure: Compilation failure: 
[ERROR] /Users/ash/IdeaProjects/vertx/vertx-rx/rxjava2/src/test/java/io/vertx/reactivex/test/ApiTest.java:[63,82] incompatible types: io.reactivex.Single<java.lang.String> cannot be converted to io.reactivex.Maybe<java.lang.String>
[ERROR] /Users/ash/IdeaProjects/vertx/vertx-rx/rxjava2/src/test/java/io/vertx/reactivex/test/ApiTest.java:[69,68] incompatible types: io.reactivex.Single<java.lang.String> cannot be converted to io.reactivex.Maybe<java.lang.String>
```

If I skip tests, builds without issue. I've got it in a project now so will try it out and give any feedback.

**Comment by vietj** [comment] 2017-06-24 07:05
you need to install this branch as well before https://github.com/vert-x3/vertx-codegen/tree/type-use-fix

**Comment by vietj** [comment] 2017-06-25 12:13
duplicate of https://github.com/vert-x3/issues/issues/273, please continue conversation there

**Closed as completed** 2017-06-25 12:13 UTC
Labels: invalid
