### ISSUE TITLE
A Question about Transaction For Mongo&MySQL

### ISSUE THREAD

**Issue by MrXionGe** [vert-x3/issues#437] opened 2018-12-24 16:26 UTC
I'm from an old note.--Here--https://groups.google.com/forum/?fromgroups=#!topic/vertx/duFVIcSR0zg%5B1-25%5D
This is a small idea. About transaction...
In future versions. Will we add some new methods? For simpler transaction usage.
And I didn't find a good way to use transactions in VertX.
Recently I've been using VertX and Mongo.VertX much more interesting than SpringBoot.It's just that there's a problem here in transactions.

**Comment by tsegismont** [comment] 2019-01-02 11:49
Closing as duplicate of https://github.com/eclipse-vertx/vert.x/issues/2781

**Closed as completed by tsegismont** 2019-01-02 11:49 UTC
Labels: duplicate
