### ISSUE TITLE
RedisClient PubSub documentation needs a fix

### ISSUE THREAD

**Issue by tlarevo** [vert-x3/issues#120] opened 2016-05-23 06:22 UTC
In the RedisClient documentation [Pubsub section](http://vertx.io/docs/vertx-redis-client/java/#_pub_sub_mode)

```java
vertx.eventBus().<JsonObject>consumer("redis.sub.channel1", received -> {
  // do whatever you need to do with your message
  JsonObject value = received.body().getJsonObject("value");
  // the value is a JSON doc with the following properties
  // channel - The channel to which this message was sent
  // pattern - Pattern is present if you use psubscribe command and is the pattern that matched this message channel
  // message - The message payload
});
```

consumers channel is written as `redis.sub.channel1` but it should be corrected as `io.vertx.redis.channel1` as follows

```java
vertx.eventBus().<JsonObject>consumer("io.vertx.redis.channel1", received -> {
  // do whatever you need to do with your message
  JsonObject value = received.body().getJsonObject("value");
  // the value is a JSON doc with the following properties
  // channel - The channel to which this message was sent
  // pattern - Pattern is present if you use psubscribe command and is the pattern that matched this message channel
  // message - The message payload
});
```

I think this fix needs to be applied to Groovy, JS, Ruby and Ceylon as well.

**Comment by pmlopes** [comment] 2016-05-23 07:11
duplicate of https://github.com/vert-x3/vertx-redis-client/issues/57

**Closed by pmlopes** 2016-05-23 07:11 UTC

**Comment by tlarevo** [comment] 2016-05-23 07:15
👍 sorry about creating a duplicate issue.
